apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-single
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: swr.cn-north-4.myhuaweicloud.com/yjs-final-2023112473/mnist-ddp:v3
          imagePullPolicy: IfNotPresent
          command:
            - python
            - train_single.py
            - --epochs
            - "2"
            - --batch-size
            - "128"
            - --data-dir
            - /work/data
            - --cpu
            - --allow-synthetic
            - --synthetic-size
            - "6000"
          resources:
            requests:
              cpu: "300m"
              memory: "768Mi"
            limits:
              cpu: "1"
              memory: "2Gi"
