apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: integral-mpi
  namespace: default
spec:
  slotsPerWorker: 2
  runPolicy:
    cleanPodPolicy: None
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - name: launcher
              image: swr.cn-north-4.myhuaweicloud.com/yjs-final-2023112473/yjs-mpi:v2
              command:
                - mpirun
                - --allow-run-as-root
                - --oversubscribe
                - -n
                - "4"
                - python
                - /opt/mpi/integral_mpi.py
                - --steps
                - "10000000"
    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - name: worker
              image: swr.cn-north-4.myhuaweicloud.com/yjs-final-2023112473/yjs-mpi:v2
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
