apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: mpi-pi
  namespace: default
spec:
  slotsPerWorker: 2
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
            - name: launcher
              image: swr.cn-north-4.myhuaweicloud.com/<YOUR_ORG>/yjs-mpi:v1
              command:
                - mpirun
                - -n
                - "4"
                - python
                - /opt/mpi/pi_mpi.py
    Worker:
      replicas: 2
      template:
        spec:
          containers:
            - name: worker
              image: swr.cn-north-4.myhuaweicloud.com/<YOUR_ORG>/yjs-mpi:v1
              resources:
                requests:
                  cpu: "1"
                  memory: "1Gi"
