apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: swr-secret
      containers:
        - name: backend
          image: swr.cn-north-4.myhuaweicloud.com/yjs-final/yjs-backend:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
